spring:
  application:
    name: jxw-provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    initial-size: 10
    max-active: 50
    max-wait: 1000
    min-idle: 10
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/jxw?serverTimezone=Asia/Shanghai

  redis:
    host: 127.0.0.1
    password:
    port: 6379
    useSsl: false

  cloud:
    nacos:
      config:
        server-addr: 192.168.1.111:8848,192.168.1.111:8849,192.168.1.111:8850


jpa:
  database: mysql
  database-platform: mysql
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL57Dialect
server:
  port: 8080

