spring:
  datasource:
    username: root
    password: pwd12345
    url: jdbc:mysql://localhost:3306/jxw?serverTimezone=Asia/Shanghai

jpa:
  database: mysql
  database-platform: mysql
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQL57Dialect
